#ifndef AN_ERROR_CODE
#define AN_ERROR_CODE


enum An_Error_Code {
	NO_EXCEPTION,
	POINTER_TO_THE_TEMPERATURE_IS_NULL_EXCEPTION,
	NOT_DIVISIBLE_BY_ONE_HUNDREDTH_EXCEPTION,
	TEMPERATURE_VALUE_LESS_THAN_LOWER_LIMIT_EXCEPTION,
	TEMPERATURE_VALUE_GREATER_THAN_UPPER_LIMIT_EXCEPTION
};


void Evaluate(An_Error_Code the_error_code_to_use);


#endif